[project]
name = "getting-started-with-dbt-on-snowflake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-snowflake>=1.10.0",
]
